### ISSUE TITLE
Can you elaborate on `lispy` vs `paredit`?

### ISSUE THREAD

**Issue by port19x** [enzuru/.emacs.d#2]
So far I've only done the extremely small subset of paredit that is `paredit-forward-slurp-sexp`.

I have briefly tested `evil-cleverparens`, only to be disappointed by it frequently leaving whitespace around sexp borders after slurp and barf operations.

What makes lispy nice for navigation and lisp coding?

**Comment by enzuru** [comment]
What makes Lispy nice is that it turns on modal editing whenever you are on parens, and you only need to hit one key, such as `e` to evaluate the s-expression.

However, Lispy is broke right now as the maintainer has disappeared, so many of us are running forked versions. I might fork it myself soon.

**Comment by port19x** [comment]
You seem like a good candidate to make a nice fork of it. Let me know when you do

**Comment by enzuru** [comment]
@port19x  I'm glad you pushed me to do it, because I finally did it: https://github.com/enzuru/lispy

**Comment by port19x** [comment]
Good work :)
